name: CI

on:
  push:
    branches:
      - main  # ou votre branche principale
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # ou la version que vous utilisez

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Deploy (optionnel)
      run: echo "Déploiement ici"  # remplacez par votre commande de déploiement